### ISSUE TITLE
библиография очень срочно

### ISSUE THREAD

**Issue by agricolamz** [daneelsteel/culturomics#1]
@daneelsteel, @nevmenandr

я наконец сел за отчет и обнаружил, что литература не в том формате. Можете пожалуйста привести и в тексте и в таблице к нужному виду?

- Должны быть следующие поля.

BIBTEXKEY | AUTHOR | TITLE | YEAR | PUBLISHER | ADDRESS | PAGES | BOOKTITLE | EDITOR | JOURNAL | NOTE | NUMBER | SCHOOL | URL | VOLUME | SERIES

- В полях автора и редактора все имена разделяются разделителем `and`, например, 

```
Gu, Yu and Tinn, Robert and Cheng, Hao and Lucas, Michael and Usuyama, Naoto and Liu, Xiaodong and Naumann, Tristan and Gao, Jianfeng and Poon, Hoifung
```

**Comment by daneelsteel** [comment]
а если в колонке ничего не написать, например, нет JOURNAL или NOTE, чем заполнять?

**Comment by agricolamz** [comment]
Ничем

**Comment by daneelsteel** [comment]
поправила, гляньте

**Comment by agricolamz** [comment]
Спасибо, не идеально, но я решил сам поправить
